# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorereleaser < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://support.cimpress.cloud/hc/en-us/articles/227873908"
  version "0.1.15"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/gorereleaser/0.1.15/gorereleaser_0.1.15_Darwin_x86_64.tar.gz"
      sha256 "c7d403abe6f41bfc77efacc9e64558629a0d559b537478bf9b621813054b5c4b"
    end
    if Hardware::CPU.arm?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/gorereleaser/0.1.15/gorereleaser_0.1.15_Darwin_arm64.tar.gz"
      sha256 "3ef20b9e2cc46e0aedfd0096e4196881c42da5007030c2cd1bd94c5fe56d741f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/gorereleaser/0.1.15/gorereleaser_0.1.15_Linux_x86_64.tar.gz"
      sha256 "465b41d3965ecc65462f70c2d21c4b64afa04d90c7a76578bd4fe05286814c73"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/gorereleaser/0.1.15/gorereleaser_0.1.15_Linux_arm64.tar.gz"
      sha256 "39df002013c1d77b152750f2e0442b1c240103b7ffb18a0890f0ec8c94c4292e"
    end
  end

  def install
    bin.install "gorereleaser"
  end

  def caveats; <<~EOS
    This is a helpful message to make people happy.
  EOS
  end

  test do
    system "#{bin}/gorereleaser"
  end
end
