# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorereleaser < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://support.cimpress.cloud/hc/en-us/articles/227873908"
  version "0.1.12"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/28251648/-/releases/v0.1.12/downloads/gorereleaser_0.1.12_Darwin_x86_64.tar.gz"
      sha256 "9a7ef9f0dec1f2e5e19101e3f5b4bb5a404d5003b8ad26fc919aaa2fb65f0788"
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/28251648/-/releases/v0.1.12/downloads/gorereleaser_0.1.12_Darwin_arm64.tar.gz"
      sha256 "12d5999daa6e79c63928ef7f3adf67e96782b30fe4d8aeb3d08f37f6bea5fcb6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/28251648/-/releases/v0.1.12/downloads/gorereleaser_0.1.12_Linux_x86_64.tar.gz"
      sha256 "f8687d2bc6e3bf2d6d0d21cd5fa9fa926f377fe844fb3e53b09ff87e5c9099f8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/28251648/-/releases/v0.1.12/downloads/gorereleaser_0.1.12_Linux_arm64.tar.gz"
      sha256 "87de3fda9c31aa3ea8429d9ebebe116bdbe56a862aad66775806d26c6c7850f3"
    end
  end

  def install
    bin.install "gorereleaser"
  end

  def caveats; <<~EOS
    This is a helpful message to make people happy.
  EOS
  end

  test do
    system "#{bin}/gorereleaser"
  end
end
