# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserTestProj < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://support.cimpress.cloud/hc/en-us/articles/227873908"
  version "0.1.10"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/28251648/-/releases/v0.1.10/downloads/GoReleaser-TestProj_0.1.10_Darwin_x86_64.tar.gz"
      sha256 "b8973c9717e8a8fa94bc098a25dd386045baf630a5e8717c379b8e11ec38fa5d"
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/28251648/-/releases/v0.1.10/downloads/GoReleaser-TestProj_0.1.10_Darwin_arm64.tar.gz"
      sha256 "0e889a51cb846dc00dd4798e15bef28675658caea86ab5c3d7b6f692e770f07e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/28251648/-/releases/v0.1.10/downloads/GoReleaser-TestProj_0.1.10_Linux_x86_64.tar.gz"
      sha256 "8dabc1061a2aebab889f2679c8b503e20157f47761e18494686430d8426ae581"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/28251648/-/releases/v0.1.10/downloads/GoReleaser-TestProj_0.1.10_Linux_arm64.tar.gz"
      sha256 "ef2e53c2ca23f2a77b1845e1870dca60ed0ced02c651cefe2c9913f0b1da12fd"
    end
  end

  def install
    bin.install "GoReleaser-TestProj"
  end

  def caveats; <<~EOS
    This is a helpful message to make people happy.
  EOS
  end

  test do
    system "#{bin}/stskeygen --version"
    ...
  end
end
