# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stskeygen < Formula
  desc "A commandline utility for trading directory service credentials (such as AD username and password) for AWS STS Keys."
  homepage "https://support.cimpress.cloud/hc/en-us/articles/227873908"
  version "2.1.12"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Darwin_x86_64.tar.gz"
      sha256 "c9a058640bb0e211437700ba6b70de815c15556e0923cb714644207d3422af00"
    end
    if Hardware::CPU.arm?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Darwin_arm64.tar.gz"
      sha256 "40218aa94f8b70b417ff2bf3ff8e4f5aee9645aafab09c32450ad50156dfd63b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Linux_x86_64.tar.gz"
      sha256 "1a2dbc63189a238f70e1a9469f57dca53b98befdebe75bb717ba3ccd0178cb3a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Linux_arm64.tar.gz"
      sha256 "f65cfbcd2f9343b0e12c11e9c3f89c7f04ec8827e43341f7b4a047ec7d0b2314"
    end
  end

  def install
    bin.install "stskeygen"
  end

  test do
    system "#{bin}/stskeygen"
  end
end
