# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stskeygen < Formula
  desc "A commandline utility for trading directory service credentials (such as AD username and password) for AWS STS Keys."
  homepage "https://support.cimpress.cloud/hc/en-us/articles/227873908"
  version "2.1.12"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Darwin_x86_64.tar.gz"
      sha256 "92860b695a574fb6b5f95efc59be1cee0d1d373d13248754cc72246b9157dc54"
    end
    if Hardware::CPU.arm?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Darwin_arm64.tar.gz"
      sha256 "b605e00e2d60190c1aadc324e8e8f1b15c831ff91ecfe2ab90d128854091ccdf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Linux_x86_64.tar.gz"
      sha256 "56d87b1d5a5f7a72295775947105c855c9885494a5c6ee0fb737e5a9adbfe1bf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gorereleaser-tst.s3.us-east-1.amazonaws.com/stskeygen/2.1.12/stskeygen_2.1.12_Linux_arm64.tar.gz"
      sha256 "c7940d34fc4f4d4fdf9fc2af79de3ba2b41861ff419e924cbdbc0ec6b7dbe9b9"
    end
  end

  def install
    bin.install "stskeygen"
  end

  test do
    system "#{bin}/stskeygen"
  end
end
